apiVersion: v1
kind: Service
metadata:
  name: rusty-async-fibber
  namespace: yournamespace
spec:
  selector:
    app: rusty-async-fibber
  ports:
    - name: fibber-socket
      protocol: TCP
      port: 1234
      targetPort: 1234
    - name: fibber-http
      protocol: TCP
      port: 80
      targetPort: 8080
